name: my Docker Action
description: 'This actions says hello to a user or a world'

inputs:
  who-to-greet:
    description: 'Who to greet' 
    required: true 
    default: 'world!!!' 
outputs: 
  time:
    description: 'The time we said hello!'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }} 

  
