name: GitHub Actions Demo 

on:
  push: 
    branches: [ main ]
    paths-ignore: [.github/** ] 
  pull_request: 
    branches: [ main ]
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs: 
  Build:
    runs-on: ubuntu-22.04
    steps:
     - run: |
          echo "Event that triggered the workflow: ${{ github.event_name }}"
          echo "The repository is referencing the current branch: ${{ github.ref }} "
          
     - uses: actions/checkout@main 

     - name: List of files in my repository
       run: tree 
       
      
        
      
  

  
