name: My First Action 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 

      - name: Run a one-line script 
        run: echo Hello World! 

      - name: Run a multi-line script
        run: |
          echo My first line of action
          echo I want to use actions to test, and deploy my project/application 
